import org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener;
public class FunctionUse881 {
public void funcUse() {
OneTimeExecutionApplicationContextEventListener onetimeexecutionapplicationcontexteventlistener = new OneTimeExecutionApplicationContextEventListener();
onetimeexecutionapplicationcontexteventlistener.setApplicationContext(null);
}
}